### PR TITLE
fix: Category Aware Search Profile not applied on Category Page (#5510)

### LINKED ISSUE #5510: Adaptive Search Profile is not applied on Category Page
## Environment Details

- Spartacus:  1.2.0

## Steps to Reproduce

1. Prepare Category Aware Search Profile (to be done in Adaptive Search) with some configuration e.g promoted products.
2. Make sure configuration is synchronized to online catalog version.
3. Navigate to category with adaptive search changes applied.
4. Search Profile changes for category is not applied.

## Observed Results
Requests sent from spartacus does not narrow down search to category and rather treat category as facet.

## Expected Results
Category Aware Search Profile changes are applied Category Page

## Offer to Fix
No

## Additional Information
Simple Search Profile works fine. Problem is only occurring for Category Aware Search Profile.
On old storefront it works fine.

### PR DESCRIPTION
**Pull request by neilhubertprice**
When using Adaptive Search only Global profiles were applying, but not
category profiles.  This is because Adaptive Search expects the use of
the allCategories field (either as a Filter Query or a Facet Value) to
mark a category page query.

This affects both categories and brands (previouly using the category
and brand facets respectively).  Both have been changed to query on
the allCategories field.

The JSP storefronts all use the allCategories field for all category
page requests & do not differentiate between category/brand/etc when
querying.

closes #5510

### CODE REVIEW

**Comment by neilhubertprice** [comment]
Also fixed CategoryPageMetaResolver to understand the allCategories facet.

Note: Commerce setup needs modifying for this to work correctly.  The
allCategories facet by default has no Facet Value Display Name Provider
set.  Without that the breadcrumb displays the code rather than the name.
Set this to the same as the category facet (categoryFacetDisplayNameProvider)
to have proper names in the breadcrumb

**Comment by tobi-or-not-tobi** [comment]
Good stuff @neilhubertprice that was the missing piece. I've created a PR to our sample data, although it's not blocking us to move forward. I'll re-start reviewing this ticket.

**Comment by tobi-or-not-tobi** [comment]
(oops wrong button ;) )

**Comment by tobi-or-not-tobi** [comment]
This PR is blocked by 2 things:
- the pipeline seems blocked for external contributors (TODO for @hackergil)
- the change in this PR could be considered a breaking change, we might want to move this to the 2.0 branch.

**Comment by neilhubertprice** [comment]
Ok, new PR at [https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/6096]

**Comment by Xymmer** [comment]
Will be QA'd with #6581, move to accepted when tested

**Comment by tobi-or-not-tobi** [comment]
QA:

(@KateChuen  feels like this was QAd before..., if so, feel free to skip)

- evaluate that the configurable topvalues in the backend is picked up in Spartacus UI; the topvalues (default to 5) should be listed immediately, while the rest is hidden behind a "show more" button. 
- evaluate that other facets will have a max of 6 values listed.

**Comment by KateChuen** [comment]
This was tested in ticket https://github.com/SAP/spartacus/issues/5692

**Pull request closed without merging**
