### PR TITLE
fix: Navigation links are smaller than hoverable components (GH…

### LINKED ISSUE #3275: Navigation links are smaller than hoverable components
After hover on navigation, css is changed but I can't click link
image
Link is available only after hover text inside
image

### PR DESCRIPTION
**Pull request by RadhepS**
Closes #3275

### CODE REVIEW

**Comment by Pucek9** [comment]
QA done, I think padding under text is also necessary. On hover under text in expansible navigation, we can see wrapper, but nav style is not changed to hovered (text should be red)
Before:
image
After:
image

**Comment by RadhepS** [comment]
Fixed

**Comment by Pucek9** [comment]
Main nav is looking and working correct, but now sub navs has too large paddings
image

**Comment by RadhepS** [comment]
Fixed.

Also reduced padding on sub navs from the original develop so it looks better.

**Pull request merged**
